### ISSUE TITLE
parsescript.py fails somehow?

### ISSUE THREAD

**Issue by mwufi** [YURAresearch/YURAResearchDatabase#14]
NOt suppose to happen

```
Traceback (most recent call last):
  File "parsedept.py", line 11, in <module>
    from bs4 import BeautifulSoup as bs
  File "/home/zen/anaconda2/lib/python2.7/site-packages/bs4/__init__.py", line 32, in<module>
    from .element import (
ImportError: cannot import name e
```

**Comment by mwufi** [comment]
Huh. Strange. I uninstalled and reinstalled bs4 and it works fine now.
